- hosts: localhost
  gather_facts: false 
  become: yes 

- name: site osp istances playbooks
  import_playbook: site-osp-instances.yml

- name: aws provision prod playbooks
  import_playbook: aws_provision.yml

- name: three teir app playbook
  import_playbook: site-3tier-app.yml

  roles:
    - config-tower
